### ISSUE TITLE
assistance understanding assets and es build in production

### ISSUE THREAD

**Issue by webdz9r** [nickjj/docker-flask-example#22]
Hi Nick, 

It's me again, I'm new to ES build / Flask and fancy node based frontend stuff... 

I've got an app in production and I'm seeing my logs continuesly state that it's rebuilding CSS and JS

```css-1    | Rebuilding...
css-1    |
css-1    | Done in 1439ms.
css-1    |
css-1    | Task completed in 0m2.511s
css-1    | Browserslist: caniuse-lite is outdated. Please run:
css-1    |   npx update-browserslist-db@latest
css-1    |   Why you should do it regularly: https://github.com/browserslist/update-db#readme
css-1    |
css-1    | Rebuilding...
css-1    |
css-1    | Done in 1526ms.
css-1    |
css-1    | Task completed in 0m2.515s
js-1     |
js-1     | Task completed in 0m0.352s
css-1    | Browserslist: caniuse-lite is outdated. Please run:
css-1    |   npx update-browserslist-db@latest
css-1    |   Why you should do it regularly: https://github.com/browserslist/update-db#readme
css-1    |
css-1    | Rebuilding...
css-1    |
css-1    | Done in 1534ms.
css-1    |
css-1    | Task completed in 0m2.572s```

I thought in production this was to be build once and not again, it seems the `production` and debug flags are a bit off too, when I put things in production I still had to modify the docker container to set the values to `False` vs `false` in the config.settings.py

Any advise on better understand prod vs dev?

**Comment by nickjj** [comment]
Hi,

This is documented in the `.env` file with a comment: https://github.com/nickjj/docker-flask-example/blob/93af9f4fbf185098ffb1d120ee0693abcd77a38b/.env.example#L15

For production mode, you'll want to make sure all 4 of these are set:

```sh
export COMPOSE_PROFILES=postgres,redis,web,worker
export DOCKER_WEB_VOLUME=./public:/app/public
export FLASK_DEBUG=false
export NODE_ENV=production
```

Technically the last 2 are the default values, so by not setting them you get the same effect.

Once you've done that then you can `docker compose build` to build your image that'll have assets precompiled and then they will be served in production directly without tailwind and esbuild running. Each asset file will also be digested too with an md5 checksum which you can verify by viewing the source of the page.

**Comment by webdz9r** [comment]
Hi Nick, 

thanks for the response. In production I was getting the debug toolbar until I changed `config/settings.py` to use strict values

```
-SECRET_KEY = os.getenv("SECRET_KEY", "supersecret")
-DEBUG = bool(strtobool(os.getenv("FLASK_DEBUG", "false")))
-PROFILE = bool(strtobool(os.getenv("FLASK_PROFILE", "false")))

+SECRET_KEY = "xxxxxxx"
+
+DEBUG = False
```

Maybe it was a cached build problem, I'm not sure

**Comment by nickjj** [comment]
Hmm you can always run `docker compose build --no-cache` to get a fresh build without cache coming into play.

**Comment by webdz9r** [comment]
is it normal to have the JS and CSS rebuild like that in the background - I assume that means it's rebuilding something and configuration is not right

**Comment by nickjj** [comment]
> is it normal to have the JS and CSS rebuild like that in the background

In my previous comment I mentioned setting `export COMPOSE_PROFILES=postgres,redis,web,worker` , did you set that? That would prevent tailwind and esbuild from running.

> Once you've done that then you can docker compose build to build your image that'll have assets precompiled and then they will be served in production directly without tailwind and esbuild running when you next docker compose up the project. Each asset file will also be digested too with an md5 checksum which you can verify by viewing the source of the page.

**Comment by webdz9r** [comment]
I have the following set as I'm not using celery or postgres at the moment
`export COMPOSE_PROFILES=redis,assets,web`

**Comment by nickjj** [comment]
In that case the JS and CSS won't get recompiled or run in the background. They are precompiled once at Docker image build time and then served on each request by either gunicorn or nginx if you add that into that mix.

**Comment by webdz9r** [comment]
could you help me understand the function for this variable `FLASK_SKIP_DOTENV="true" \` 

Seems that we always want env variables?

**Comment by nickjj** [comment]
Yes, that stemmed from this issue: https://github.com/pallets/flask/issues/3872

**Comment by webdz9r** [comment]
another item - when trying to add [tailwind/forms](https://github.com/tailwindlabs/tailwindcss-forms)

I've added this to my Dockerfile for the asset pipeline
`RUN npm install -D @tailwindcss/forms`

edit my tailwind.config.js
```
module.exports = {
  content: [
    '/app/assets/js/**/*.js',
    '/app/assets/css/**/*.css',
    '/app/teetime/**/*.html',
    './node_modules/preline/dist/*.js'
  ],
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
    require('preline/plugin')
  ],
  darkMode: 'class'
}
```

when I run `docker compose build` and `docker compose up`

```
web-1    | [2024-05-08 16:06:51 +0000] [1] [INFO] Starting gunicorn 21.2.0
web-1    | [2024-05-08 16:06:51 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
web-1    | [2024-05-08 16:06:51 +0000] [1] [INFO] Using worker: sync
web-1    | [2024-05-08 16:06:51 +0000] [7] [INFO] Booting worker with pid: 7
css-1    | 
css-1    | Rebuilding...
css-1    | Error: Cannot find module '@tailwindcss/forms'
css-1    | Require stack:
css-1    | - /app/assets/tailwind.config.js
css-1    |     at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
css-1    |     at Function.resolve (node:internal/modules/helpers:136:19)
css-1    |     at _resolve (/node_modules/jiti/dist/jiti.js:1:251148)
css-1    |     at jiti (/node_modules/jiti/dist/jiti.js:1:253746)
css-1    |     at /app/assets/tailwind.config.js:9:5
css-1    |     at evalModule (/node_modules/jiti/dist/jiti.js:1:256443)
css-1    |     at jiti (/node_modules/jiti/dist/jiti.js:1:254371)
css-1    |     at /node_modules/tailwindcss/lib/lib/load-config.js:48:30
css-1    |     at loadConfig (/node_modules/tailwindcss/lib/lib/load-config.js:50:6)
css-1    |     at Object.loadConfig (/node_modules/tailwindcss/lib/cli/build/plugin.js:135:49) {
css-1    |   code: 'MODULE_NOT_FOUND',
css-1    |   requireStack: [ '/app/assets/tailwind.config.js' ]
css-1    | }
```

**Comment by nickjj** [comment]
Hi,

You don't need to add the `RUN` instruction. You can run `./run yarn:install` after adding the dependency to your package.json file and it will take care of installing any new dependencies and also write out a new lock file. The readme file has this documented: https://github.com/nickjj/docker-flask-example?tab=readme-ov-file#updating-dependencies

**Comment by webdz9r** [comment]
does this behavior change from production vs development?

**Comment by nickjj** [comment]
Yes, that's also mentioned in the docs and blog posts linked in the readme file.

In production assets will get digested and saved in a spot so you can reference them from a web server without needing to run the `css` or `js` containers.

**Comment by webdz9r** [comment]
I'm so close to getting this all sorted out... 

I'm trying to install [preline](https://preline.co/docs/index.html)

yarn is doing it's thing properly but it seems that flask needs the /node_module/preline/dist/*.js files in order to work. What is the proper way to make those files available inside the application container. Seems that docker is only coping the /app/public folder

**Comment by nickjj** [comment]
Hi, I never used that package. I'm not super well versed with esbuild but I wonder if there's anything you can do or configure to have it copy those files to a destination directory so you don't need to modify your Dockerfile.
